name: "Sync MONITORING"

on:
  push:
    branches:
      - "main"

jobs:
  sync:
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [arm64, x64]
    steps:
    - uses: actions/checkout@master
    - name: Login to GH Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Install yq
      run: |
        sudo apt-get update && sudo apt-get install -yqq yq wget
    - name: Iterate
      run: |
        yq --version
        docker run --rm quay.io/skopeo/stable:v1.9.2 --version
        ./single_sync.sh modules/monitoring/images.yml false
